### ISSUE TITLE
A composable workflow module

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#166]
Currently, the processes are scheduled manually or the workflows are developed manually per each execution. This workflow module will enable chaining of processes:

One common workflow is, cold-extraction -> png-extraction, which will retrieve the images and then convert the DICOM images to PNG images and extract metadata.

Another workflow we use is for scanner utilization. It is, cold-extraction -> png-extraction -> scanner-util.

The aim is to reduce human-in-the-loop in several repeated execution patterns we have.

**Comment by anbhimi** [comment]
Integrated Modality Splitting, PNG Extraction, DICOM Anonymization, and Metadata Anonymization. But Cold Extraction is not working in the workflows.

**Comment by pradeeban** [comment]
Closing this issue since a Nextflow-based prototype is currently implemented.

**Comment by pradeeban** [comment]
Current status with Nextflow - https://github.com/Emory-HITI/Niffler/tree/dev/modules/workflows/Nextflow_workflows
