### ISSUE TITLE
Support extracting Private DICOM tags using the png-extraction

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#258]
Currently, the png extraction module supports extracting only public DICOM attributes. Extending it to support private tags can significantly help research works that depend on those.

**Comment by Pavan-Bellam** [comment]
Hello, I am working on this issue.

**Comment by pradeeban** [comment]
ok, thanks for the update.

**Comment by Pavan-Bellam** [comment]
Hi @pradeeban, in some DICOM files there would be some private tags which the user does not want to extract such as histogram tag shown  in the picture below. What I would like to do is extract only the tags whose value length is less than certain threshold.  Is there any other way to handle this better?  
![image](https://user-images.githubusercontent.com/60264606/158318683-4402ab2d-d3b8-4b1a-975b-4a236fec08f2.png)

**Comment by pradeeban** [comment]
This is a good question. So let me answer in detail.

If you check https://github.com/Emory-HITI/Niffler/blob/dev/modules/png-extraction/ImageExtractor.py, you will see the below lines:
    # dicom images should not have more than 300 dicom tags
    if len(kv)>300:

So, we are ignoring images with more than 300 attributes. Similarly, you could use the first/easy approach you mentioned (extract only the tags whose value length is less than a certain threshold).

You likely will need to add a property in https://github.com/Emory-HITI/Niffler/blob/dev/modules/png-extraction/config.json

	"PublicHeadersOnly": true,

The above default will ensure by default only public headers will be extracted. When you set that to false, you will also extract the private headers. This will ensure that we are not bombarding users with private tags all the times (most users do not need those, and that is why we did not have this implemented for long).

Your second option is the ideal scenario. That is how the meta-extraction module handles its extraction. It uses a featureset. See https://github.com/Emory-HITI/Niffler/blob/dev/modules/meta-extraction/conf/featureset.txt

Ideally, we should have both options for the png-extraction. When the featureset is present, get only those listed fields. Otherwise, get everything (as it is now, but without the private tags for now).

**Comment by Pavan-Bellam** [comment]
Thank you for the answer. I will modify the code such that both the options are available for the user.

**Comment by Nitesh639** [comment]
Hy @pradeeban , I have solved this issue.  Please check it.

**Comment by pradeeban** [comment]
@Nitesh639 I have requested changes to your pull request.

**Comment by Nitesh639** [comment]
@pradeeban I make changes. Check now.

**Comment by pradeeban** [comment]
Fixed by @Nitesh639 in Niffler-0.8.5.
