### ISSUE TITLE
Containerize PNG Extraction module

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#262]
This is an easy candidate for Docker containerization. It will be a helpful feature since dependencies such as gdcm tend to have conflicts when locally installed. A containerized module will solve that challenge.

Running [install.sh](https://github.com/Emory-HITI/Niffler/install.sh) in the container will install the dependencies. Please do a test on a sample image (such as one that could be obtained from https://www.cancerimagingarchive.net/collections/ ) to confirm it is working, before committing the changes or creating a pull request. Also, please include README instructions on how this could be run as a container so people could already start using your container.

**Comment by pradeeban** [comment]
Welcome, @pramit026.

https://github.com/Emory-HITI/Niffler/tree/master/modules/png-extraction is the module that should be containerized. 

https://github.com/Emory-HITI/Niffler/blob/master/install.sh is an installation script that installs the prerequisites and dependencies. So your container should include those commands to install those (for example, gdcm).

**Comment by pradeeban** [comment]
Sure, @Nitesh639. Thanks.

**Comment by Nitesh639** [comment]
@pradeeban I'm getting error while installing  backend dependencies: finished with status 'error' . How can I solve it.

**Comment by Nitesh639** [comment]
FROM python

WORKDIR /modules

COPY png_extraction .

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD [ "python", "./ImageExtractor.py"]



# this is my code

**Comment by Nitesh639** [comment]
I have made PR. Merge the changes.

**Comment by pradeeban** [comment]
Thanks, @Nitesh639, for your contribution. Your pull request is now merged.
