### ISSUE TITLE
MemoryError while extracting metadata using PNG Extraction Module

### ISSUE THREAD

**Issue by anbhimi** [Emory-HITI/Niffler#267]
While extracting metadata using the PNG Extraction Module (CommonHeadersOnly - true), all the DICOM tags are collected stored in a CSV format using pandas. 

The memory error occurs because - in some instances, the DICOM Images could have a large no. of tags than expected which creates a sparse CSV file resulting in a large data frame that cannot be saved using pandas.

The error can be fixed by transferring such DICOM files (which have a large no. of tags) into a new folder in `failed-dicom` folder in the same module.

**Comment by anbhimi** [comment]
Fixed the issue in PR - 271. But did not transfer the failing DICOMs to a new folder. I will submit a new PR to perform the operation.

**Comment by Nitesh639** [comment]
Hy @anbhimi & @pradeeban, Please give me example of  the DICOM Images who have a large no. of tags than expected.

**Comment by Nitesh639** [comment]
@pradeeban ok

**Comment by pradeeban** [comment]
Fixed by @anbhimi

**Comment by pradeeban** [comment]
#293
