### ISSUE TITLE
png-extractor module not working in arch linux

### ISSUE THREAD

**Issue by Nitesh639** [Emory-HITI/Niffler#268]
I have installed all the python dependencies, gdcm (yay -S gdcm). Then I placed dicom image and modified config as required. It generates all the folders but generates no png file and shows no error. I expect a png image in my output directory.  
I am attaching ImageExtractor.out, i.e. the log file with it.
It shows there are no files in that folder though there are files present.

[ImageExtractor.out.txt](https://github.com/Emory-HITI/Niffler/files/8191074/ImageExtractor.out.txt)
[ImageExtractor.pickle.txt](https://github.com/Emory-HITI/Niffler/files/8191075/ImageExtractor.pickle.txt)

python that I have is 3.10.4

**Comment by pradeeban** [comment]
Let's see what is happening.

That error usually means you do not have the files present in the expected directory or in the expected hierarchy.


{
	"DICOMHome": "/opt/data/new-study",
	"OutputDirectory": "/opt/data/new-study/root",
	"Depth": 0,
	"SplitIntoChunks": 1,
	"PrintImages": true,
	"CommonHeadersOnly": false,
	"UseProcesses": 0,
	"FlattenedToLevel": "patient",
	"is16Bit":true,
	"SendEmail": true,
	"YourEmail": "test@test.test"
}

Can you please attach your config.json of the png-extractor module?

Then also attach the folder hierarchy of the DICOMHome folder. You can achieve that by running:
 tree DICOMHome > tree.txt 

(of course, replacing DICOMHome above in the tree command with the correct DICOMHome you have set. You will need to install "tree", if you do not have it installed.
https://archlinux.org/packages/extra/x86_64/tree/
)

**Comment by Nitesh639** [comment]
Thank you for helping me debug. It was a mistake from my side. I was using DCM files with extension in Capital letters.
