### ISSUE TITLE
Random PNG Extraction Errors

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#273]
The png-extraction modules occasionally throw the below errors.

* Multiprocessing Error

* No error but metadata file is not created - Process Killed.

* RuntimeWarning: invalid value encountered in true_divide

They are hard to reproduce. But recording here for future reference.

**Comment by zmz223** [comment]
TypeError: Could not convert value to integer without loss

**Comment by anbhimi** [comment]
Fixed the second error (No error but metadata file is not created - Process Killed) - Memory Error through PR #306. The final part of the error has been tracked through Issue #307.
