### ISSUE TITLE
Niffler commit workflows are faling.

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#287]
The CI tests that are triggered when we commit, are failing. For example, check -

https://github.com/Emory-HITI/Niffler/actions/runs/2034155913

and

https://github.com/Emory-HITI/Niffler/runs/5675974447?check_suite_focus=true

It fails at the step:

0s
Install Python3
Run yum update -y -q
  yum update -y -q
  yum install -q -y python3 
  yum install -q -y python3-pip unzip
  shell: sh -e {0}
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error: Process completed with exit code 1.

Should be fixed as this is currently rendering the CI commit workflows useless.

**Comment by Pavan-Bellam** [comment]
Hello, I am working on this issue.

**Comment by Pavan-Bellam** [comment]
Hi @pradeeban, I suppose the issue is with centOS as it has reached its end of life.

**Comment by mehulsinha73** [comment]
Hi @pradeeban , I have solved this issue, Please check it #288

**Comment by mehulsinha73** [comment]
Yes, I tried to fix it but i haven't familiarized myself with the code base yet. @Pavan-Bellam might be able to help out as the errors are related to #282.

**Comment by Pavan-Bellam** [comment]
The problem is with container. It might be fixed if we chage it to ubuntu. @pradeeban is it okay to change it?

**Comment by Pavan-Bellam** [comment]
And this is bot related to code. It is related to  github actions

**Comment by pradeeban** [comment]
Yes, you can try and see if that fixes.

**Comment by Pavan-Bellam** [comment]
Hey @pradeeban , I have submitted a PR regarding this issue. Could you please check it.

**Comment by pradeeban** [comment]
Hi @Pavan-Bellam, you have changed the file modules/png-extraction/ImageExtractor.py in your pull request. Why is that? This fix must fix only the files in the .workflows directory.

**Comment by Pavan-Bellam** [comment]
@pradeeban , In test_png_extraction.py we have directly called extract_headers function without calling initialize_config_and_execute where we are declaring PublicHeadersOnly and SpecificHeadersOnly as global variables. So we are getting NameError as they have not beet declared. So what I have done is instead of declaring them as global variables I have passed them as arguments to the function.

**Comment by pradeeban** [comment]
Aha, got it. I will need to test this a bit more. I will get back to this by late Monday. Thank you for your contribution.

**Comment by Pavan-Bellam** [comment]
Okay thank you!

**Comment by pradeeban** [comment]
Merged.

**Comment by pradeeban** [comment]
#295 has broken this again. @Nitesh639 can you please have a look?

**Comment by pradeeban** [comment]
Fixed in dev.

**Comment by pradeeban** [comment]
Failing again...

**Comment by anbhimi** [comment]
The test failures are the same as the ones in the previous instance. Here are more details on the test failures
1. One Integration Test Failed (PNG Extraction Module) - The failure did not appear until #326 the following changes in PNG Extraction Module might be the issue at hand.
2. Five Unit Tests Failed (Cold Extraction Module) - These failures were a result of code added to include the **StudyMonth** attribute. 

I will be working on the point 2 test failures.

**Comment by Pavan-Bellam** [comment]
I will look at point 1

**Comment by anbhimi** [comment]
Fixed the Cold Extraction Module Unit Tests at #333

**Comment by pradeeban** [comment]
Last commits have fixed the commit workflows in dev and main branches.
