### ISSUE TITLE
Support both YYYY and YY for accession

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#29]
PACS stores AccessionNumber as a string with the year in YY format compared to other clinical systems with the year in YYYY format. This variance in representations raises the problem of data quality in the queries. 

Naturally, Niffler supports only YY format since that is the DICOM default. However, supporting both YYYY and YY formats will help with diverse extraction queries.

**Comment by Pawanupadhyay10** [comment]
hello, I will like to contribute ,hey pradeeban will you help me to start .

**Comment by dbmohit** [comment]
can i contribute on this

**Comment by pradeeban** [comment]
Sure.  Feel free to.

**Comment by sumit-158** [comment]
Is anyone working on this? If not, can I work o this??

**Comment by anbhimi** [comment]
The following PR introduces support for Long Accession Numbers.

https://github.com/Emory-HITI/Niffler/pull/359

**Comment by pradeeban** [comment]
Merged to dev.
