### ISSUE TITLE
If there are large no. of mapping or metadata files - concatenating or merging them leads to a Memory Error.

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#307]
Spotted with  DICOMs of 1.1TB and 1000 metadata files (small files).

**Comment by anbhimi** [comment]
The ```MemoryError``` pops up when we have a large no. of DICOMs in the provided cohort/iteration. Thus, increasing the size of metadata and mapping data frames leads to memory errors in pandas.

A simple fix is to reduce the no. of DICOMs in the cohort leading to smaller metadata and mapping data frames that pandas could handle to merge or concatenate. The information is posted in the troubleshooting section of PNG Extraction README.md.
