### ISSUE TITLE
Packaging Niffler with pip

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#335]
This is slightly tricky since Niffler is not just Python.

Among the modules, the below are in Python: 
* cold-extraction
* dicom-anonymization
* meta-extraction
* nifti-extraction
* png-extraction
* rta-extraction
* suvpar

Although the above could be packaged with pip following [1], there are complex dependencies such as DCM4CHE as storescp for cold-extraction and meta-extraction, mongo for meta-extraction, and gdcm for png-extraction. Additional care must be taken on initiatives on packaging Niffler as an installable configuration to ensure this is complete.

[1] https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by Shazam213** [comment]
hello everyone, I would like to start working on this issue.
I have gone through the above mentioned tutorial and will try to package niffler with pip.

**Comment by pradeeban** [comment]
Thanks for your interest. Sure, go ahead!

**Comment by pradeeban** [comment]
@anbhimi Do you have time to review this change in the PR (merged above)? I have merged it as it does not change/alter existing behavior.

But my thinking is, a pip is much trickier in practice, due to the external dependencies and how Niffler interacts with other language (example: Java-based Niffler app-layer and DCM4CHE) dependencies and modules.
