### ISSUE TITLE
Containerizing Niffler

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#349]
Currently, Niffler png-extraction is containerized (#262). However, other modules are not containerized. What we propose is a global Niffler container from where different modules can be executed.

While this can be a challenging undertaking (considering the multiple modules of Niffler and dependencies on our sibling frameworks such as Eaglescope for the visualizations), an attempt at this will help us expand the user base and also will help us improve the framework itself in its compactness.

**Comment by rumbleFTW** [comment]
I was thinking about this issue, and came up with a possible approach-

1. Containerize all the modules separately.
2. Use docker compose to interconnect the docker containers that work together to provide a complete application.

Is this path viable? Or a better approach might be possible?

**Comment by pradeeban** [comment]
That is a potential path. We already have a container for the png-extraction module.

**Comment by yuvraj-wale** [comment]
Hey @rumbleFTW, are you working on this issue?

**Comment by pradeeban** [comment]
@yuvraj-wale you are free to attempt. At this point, this is more of an exercise, so some duplicate efforts are okay. We have a container for png-extraction module. Are you proposing a similar approach to that proposed by @rumbleFTW (separate container for each module?) That seems neat to me since most modules stand on their own anyway.

Among the other modules, I would say cold-extraction and meta-extraction are the most frequently used ones (with cold-extraction used much more often than meta-extraction. So you can actually start with the cold-extraction container first).

**Comment by yuvraj-wale** [comment]
Yes, I agree with the proposed approach to containerizing each module separately, I'll start by containerizing the cold-extraction module first. Thanks.

**Comment by rumbleFTW** [comment]
@yuvraj-wale Sure, you can go ahead with containerizing the cold-extraction module, and I'm continuing with the meta-extraction module.

**Comment by imiro** [comment]
Hi all! I'm interested in helping out with this effort too, any suggestion on which module should I work on? I've been able to get the frontend module running on a container, but I'm yet to test the functionalities.

**Comment by pradeeban** [comment]
The frontend module must be outdated by now, as all the backend modules have been recently updated, with frontend modules not receiving the necessary changes.

Not many used the front-end module anyway. So we can ignore that.

@yuvraj-wale and @rumbleFTW are attempting the cold-extraction and meta-extraction modules, the two important modules that are not containerized.

You are free to try containerizing any of those two as well.

**Comment by imiro** [comment]
I see, thanks for letting me know @pradeeban. Perhaps I can try to work on the meta-extraction module then

**Comment by pradeeban** [comment]
Although we did not test the newly created Dockerfiles, since this is implemented, we are closing this issue.

**Comment by pradeeban** [comment]
Thanks, @imiro for your contributions.
