### ISSUE TITLE
Anaconda reinstallation 

### ISSUE THREAD

**Issue by rumbleFTW** [Emory-HITI/Niffler#373]
**Description**
Anaconda is downloaded and installed again when install.sh is run in a system which already has anaconda installed.

**To Reproduce**
1. Have Anaconda installed already in the system.
2. Clone the repository.
3. Run install.sh

**Expected behavior**
The install script should skip installing Anaconda.

**Environment:**
 - OS: Arch Linux x86_64, Kernel: 6.1.12-arch1-1

**Comment by pradeeban** [comment]
Thanks @rumbleFTW for the great catch. Merged your PR. So this is currently fixed in dev. We periodically test and merge the dev into the master branch.
