### ISSUE TITLE
macOS_install.sh script for quick installation of dependancies for MacOS

### ISSUE THREAD

**Issue by yuvraj-wale** [Emory-HITI/Niffler#380]
**Is your feature request related to a problem? Please describe.**
The macOS install script is designed to address the problem of installing the necessary dependencies for the Niffler application on a macOS system quickly and efficiently. Without this script, users may have difficulty installing and configuring the required dependencies.

**Describe the solution you'd like**
a clear and concise solution would be to create a macOS equivalent script of the already in place install.sh script(which is for linux OS) that automates the installation process of all the necessary dependencies for the Niffler application on macOS. Additionally, it should create and configure the necessary service files (plist files) to ensure that the Niffler application and its components start automatically on system startup. The end result would be a hassle-free and straightforward installation process for Niffler on macOS.

**Describe alternatives you've considered**
An alternate solution could be a script that wound create an installable package for macOS as discussed here #374

**Comment by pradeeban** [comment]
Merged. Thanks.
