### ISSUE TITLE
syntax error in the ImageExtractorNifti.py, line 206

### ISSUE THREAD

**Issue by yuvraj-wale** [Emory-HITI/Niffler#384]
**Describe the bug**
An error message pops up "Statements must be separated by newlines or semicolons" in the ImageExtractorNifti.py file of the nifty-extraction module at line 206.

**To Reproduce**
1. Go to 'modules/nifti-extraction/ImageExtractorNifti.py''
3. Scroll down to 'line 206'

**Expected behavior**
There shouldn't be any syntax error

**Environment (please complete the following information):**
 - OS: MacOS

**Comment by pradeeban** [comment]
Merged. Thanks.
