### ISSUE TITLE
A UI for Niffler

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#72]
Develop a UI for the Niffler modules.

**Comment by Pawanupadhyay10** [comment]
hello, I will like to contribute ,hey pradeeban  will you help me to start .

**Comment by Pawanupadhyay10** [comment]
Actually, I am new to niffler.

**Comment by pradeeban** [comment]
If you are a GSoC student, please follow the Slack channel for the discussions around the GSoC.

**Comment by pradeeban** [comment]
Niffler-0.7.1 onwards a frontend is available.
