### ISSUE TITLE
Enable dynamic splitting of csv file for multi-threaded on-demand extraction

### ISSUE THREAD

**Issue by pradeeban** [Emory-HITI/Niffler#96]
Currently, this could be achieved by a human-in-the-loop. Make this an automated process.

**Comment by Nishchal-007** [comment]
For this, do we need to run the splitCSV.py file separately so that the CSV file can be split into other files?

**Comment by pradeeban** [comment]
The splitCSV.py is the current approach where we are manually splitting the CSV file into multiples. This report suggests removing that human-in-the-loop and rather dynamically route each line in the CSV to one of the 2 or more parallel extractions.

The very early start of the work is in the branch https://github.com/Emory-HITI/Niffler/compare/0.6-alpha

So this report is actually removing the dependence on splitCSV.py.

**Comment by pradeeban** [comment]
Closing as "won't fix" for now.
